### ISSUE TITLE
flarum-tags.admin.edit_tag.icon_label

### ISSUE THREAD

**Issue by ghost** [manaszon/flarum-ext-hungarian#4]
Szia! Köszi szépen a fordítást, hatalmas segítség! Találtam egy kis bugot, de nem is biztos, hogy bug csak akkor még ez a felirat más volt vagy nem létezett. Alább csatoltam egy képet a hibáról.

[Screenshot](https://imgur.com/2RKOk2k)

**Comment by manaszon** [comment]
Szia! Köszönöm, hogy jelezted.
Valóban így van, ez a felirat még nem létezett, amikor a fordítás elkészült. Átnéztem az összes (alapértelmezett) kiegészítő, illetve a core fordításait is, és ahol szükséges volt, kiegészítettem az újakkal. Kérlek frissítsd a kiegészítőt az új, 1.3-as verzióra. 
Ha esetleg az új verzióban is találsz hiányos fordításokat vagy bármi egyéb hibát, kérlek jelezd.
